// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAINPzGAKqhAFtpNkfcAf7wr_k7acD11q0',
//     appId: '1:577535068852:web:359cd68415c3d832eb25e1',
//     messagingSenderId: '577535068852',
//     projectId: 'revive-and-thrive-1d7e4',
//     authDomain: 'revive-and-thrive-1d7e4.firebaseapp.com',
//     storageBucket: 'revive-and-thrive-1d7e4.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBbIoXsCyU4CjUYOQKnJMVpD3k3tW3XWog',
//     appId: '1:577535068852:android:fdf0225d8fcbf3b8eb25e1',
//     messagingSenderId: '577535068852',
//     projectId: 'revive-and-thrive-1d7e4',
//     storageBucket: 'revive-and-thrive-1d7e4.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDRoA7_bfKpppPGBJ81AKMfuKouC8vsyRA',
//     appId: '1:577535068852:ios:4b0d6964f763a2c5eb25e1',
//     messagingSenderId: '577535068852',
//     projectId: 'revive-and-thrive-1d7e4',
//     storageBucket: 'revive-and-thrive-1d7e4.firebasestorage.app',
//     iosBundleId: 'com.example.webApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDRoA7_bfKpppPGBJ81AKMfuKouC8vsyRA',
//     appId: '1:577535068852:ios:4b0d6964f763a2c5eb25e1',
//     messagingSenderId: '577535068852',
//     projectId: 'revive-and-thrive-1d7e4',
//     storageBucket: 'revive-and-thrive-1d7e4.firebasestorage.app',
//     iosBundleId: 'com.example.webApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAINPzGAKqhAFtpNkfcAf7wr_k7acD11q0',
//     appId: '1:577535068852:web:d16ccba677271281eb25e1',
//     messagingSenderId: '577535068852',
//     projectId: 'revive-and-thrive-1d7e4',
//     authDomain: 'revive-and-thrive-1d7e4.firebaseapp.com',
//     storageBucket: 'revive-and-thrive-1d7e4.firebasestorage.app',
//   );
// }
